"""
AI Report Generator using Groq (free) API with llama-3.3-70b.
Falls back to rule-based report if no API key is set.
"""

from typing import Dict, List, Any, Optional
import httpx
import json
import structlog

from app.core.config import settings

logger = structlog.get_logger()

# ── Prompt ────────────────────────────────────────────────────────────────────

def _build_prompt(url, risk_score, overall_severity, raw_findings, vulnerabilities,
                  ssl_valid, ssl_expiry_days, response_time_ms):
    raw_text = "\n".join(
        f"  {'✓' if f.get('status')=='pass' else '✗' if f.get('status')=='fail' else '⚠'} "
        f"{f.get('check','?')}: {f.get('detail','')}"
        for f in raw_findings
    )
    vuln_text = "\n\n".join(
        f"  [{v.get('severity','?').upper()}] {v.get('name','?')}\n"
        f"    {v.get('description','')}\n"
        f"    Fix: {v.get('recommendation','')}"
        for v in vulnerabilities
    ) or "None detected."

    ssl_str = "Yes ✓" if ssl_valid else "No ✗" if ssl_valid is False else "Unknown"

    return f"""You are a senior cybersecurity expert writing a professional security report for a small business owner.

Website: {url}
Risk Score: {risk_score}/100
Overall Severity: {overall_severity.upper()}
SSL Valid: {ssl_str} | Expires in: {ssl_expiry_days or 'N/A'} days
Response Time: {response_time_ms or 'N/A'}ms

Raw Findings:
{raw_text}

Vulnerabilities ({len(vulnerabilities)} total):
{vuln_text}

Write a clear security report with these sections:
### 1. Executive Summary
### 2. Critical Issues (if any)
### 3. All Vulnerabilities Found
### 4. What's Working Well
### 5. Recommended Action Plan (Immediate / Short-term / Long-term)
### 6. Score Explanation

Keep it professional but easy to understand. Use markdown."""


# ── Groq Client ───────────────────────────────────────────────────────────────

async def _call_groq(prompt: str) -> str:
    """Call Groq free API (llama-3.3-70b-versatile)."""
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {settings.GROQ_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 2000,
                "temperature": 0.3,
            },
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"]


# ── Fallback rule-based report ────────────────────────────────────────────────

def _fallback_report(url, risk_score, overall_severity, vulnerabilities):
    emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}
    sev_e = emoji.get(overall_severity, "⚪")

    vuln_lines = "".join(
        f"### {emoji.get(v.get('severity','low'), '⚪')} [{v.get('severity','?').upper()}] {v.get('name','?')}\n"
        f"{v.get('description','')}\n\n**Fix:** {v.get('recommendation','')}\n\n"
        for v in vulnerabilities
    ) or "_No vulnerabilities detected._\n"

    urgency = "Immediate attention required." if overall_severity in ("critical", "high") \
              else "Address these issues at your earliest convenience."

    return f"""# Security Report: {url}

## Risk Score: {risk_score}/100 {sev_e}
**Overall Severity:** {overall_severity.upper()}

## Summary
This scan identified **{len(vulnerabilities)} issue(s)** on {url}. {urgency}

## Vulnerabilities Found

{vuln_lines}
## Next Steps
1. Review each issue above with your developer
2. Apply fixes in order of severity
3. Re-scan after fixes to verify improvements

---
*Generated by CyberScan.Ai Security Scanner*
"""


# ── Main entry point ──────────────────────────────────────────────────────────

class AIReportGenerator:
    async def generate_report(self, url, risk_score, overall_severity,
                               raw_findings, vulnerabilities,
                               ssl_valid, ssl_expiry_days, response_time_ms) -> str:
        if settings.GROQ_API_KEY:
            try:
                prompt = _build_prompt(url, risk_score, overall_severity,
                                       raw_findings, vulnerabilities,
                                       ssl_valid, ssl_expiry_days, response_time_ms)
                report = await _call_groq(prompt)
                logger.info("groq_report_generated", url=url, chars=len(report))
                return report
            except Exception as e:
                logger.warning("groq_report_failed", error=str(e))

        # Fallback — no API key or Groq failed
        logger.info("using_fallback_report", url=url)
        return _fallback_report(url, risk_score, overall_severity, vulnerabilities)

    def _fallback_report(self, url, risk_score, overall_severity, vulnerabilities):
        return _fallback_report(url, risk_score, overall_severity, vulnerabilities)


_instance: Optional[AIReportGenerator] = None

def get_report_generator() -> AIReportGenerator:
    global _instance
    if _instance is None:
        _instance = AIReportGenerator()
    return _instance
