import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Bot } from 'lucide-react'

export default function AIReportViewer({ report }) {
  if (!report) return null

  return (
    <div className="card p-6">
      <div className="flex items-center gap-3 mb-5 pb-4 border-b border-slate-800">
        <div className="w-9 h-9 bg-indigo-600/20 border border-indigo-500/30 rounded-lg flex items-center justify-center">
          <Bot size={18} className="text-indigo-400" />
        </div>
        <div>
          <h3 className="font-semibold text-slate-100">AI Security Analysis</h3>
          <p className="text-xs text-slate-400">Generated by GPT-3.5 via LangChain</p>
        </div>
      </div>

      <div className="prose prose-invert prose-sm max-w-none
        prose-headings:text-slate-100 prose-headings:font-semibold
        prose-h1:text-xl prose-h2:text-lg prose-h3:text-base
        prose-p:text-slate-300 prose-p:leading-relaxed
        prose-strong:text-slate-100 prose-strong:font-semibold
        prose-code:text-blue-300 prose-code:bg-slate-800 prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:text-xs
        prose-pre:bg-slate-800 prose-pre:border prose-pre:border-slate-700
        prose-ul:text-slate-300 prose-ol:text-slate-300
        prose-li:marker:text-slate-500
        prose-a:text-blue-400 prose-a:no-underline hover:prose-a:underline
        prose-hr:border-slate-800
        prose-blockquote:border-l-blue-500 prose-blockquote:text-slate-400">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {report}
        </ReactMarkdown>
      </div>
    </div>
  )
}
